#!/bin/bash


ARTIST_MAX=25
SONG_MAX=25

## ===================================================

ARTIST_LIMIT=$((ARTIST_MAX - 3))
SONG_LIMIT=$((SONG_MAX - 3))

case "$BLOCK_INSTANCE" in
    cmus)
        ARTIST="$(cmus-remote -Q | awk '$2=="artist" { $1=""; $2=""; print $0; exit }' )"
        SONG="$(cmus-remote -Q | awk '$2=="title" { $1=""; $2=""; print $0; exit }' )"
    ;;
	audacious)
		ARTIST="$(audtool --current-song-tuple-data artist)"
		SONG="$(audtool --current-song-tuple-data title)"
	;;
    *)
        echo "n/a"
        exit
    ;;
esac

if [ ${#ARTIST} -gt $ARTIST_MAX ]
then
    ARTIST=$(printf "%s..." "${ARTIST:0:$ARTIST_LIMIT}")
fi

if [ ${#SONG} -gt $SONG_MAX ]
then
    SONG=$(printf "%s..." "${SONG:0:$SONG_LIMIT}")
fi

echo $ARTIST - $SONG
