#!/bin/bash

# pgrep audacious > /dev/null
# if [ $? -eq 1 ]
# then
#     echo "-"
#     exit
# fi

ARTIST_MAX=25
SONG_MAX=25

## ===================================================

ARTIST_LIMIT=$((ARTIST_MAX - 3))
SONG_LIMIT=$((SONG_MAX - 3))

ARTIST="$(audtool --current-song-tuple-data artist)"
SONG="$(audtool --current-song-tuple-data title)"

if [ ${#ARTIST} -gt $ARTIST_MAX ]
then
    ARTIST=$(printf "%s..." "${ARTIST:0:$ARTIST_LIMIT}")
fi

if [ ${#SONG} -gt $SONG_MAX ]
then
    SONG=$(printf "%s..." "${SONG:0:$SONG_LIMIT}")
fi

echo $ARTIST - $SONG
