#!/bin/dash
ARCSIZE=$(echo $(grep -m 1 -Po '^size\ *4\ *\K\d+' /proc/spl/kstat/zfs/arcstats) " / (1024 * 1024)" | bc)
UNIT="M"

if [ $ARCSIZE -gt 1024 ]
then
    ARCSIZE=$(echo "scale=1; " $ARCSIZE " / 1024" | bc -l)
    UNIT="G"
fi

printf "%s%s" $ARCSIZE $UNIT
